name: 'Quad App Build and Push Action'
description: 'Quad App Build and Push Action'
inputs:
  app:  # id of input
    description: 'Application Name'
    required: true
    default: 'hello'
  region:  # id of input
    description: 'GCP GAR Region'
    required: true
    default: 'asia-southeast1'
  project:  # id of input
    description: 'GCP Project ID'
    required: true
    default: ''
outputs:
  version:
    description: "Version that pushed to GAR"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Add GITHUB_SHA_SHORT env property with commit short sha
      run: echo "GITHUB_SHA_SHORT=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      shell: bash

    - name: Get app version from commit message
      shell: bash
      id: version-info
      run: >-
        echo "APP_VERSION=$(
          echo ${{github.event.head_commit.message}} |
          sed -n 's/.*\[mark-\(v[0-9][0-9\.]*\)\].*/\1/p'
        )" >> $GITHUB_OUTPUT

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Build the Docker image
      shell: bash
      run: docker build . --tag ${{ inputs.region }}-docker.pkg.dev/${{ inputs.project }}/quad/${{ inputs.app }}:${{ steps.date.outputs.date }}-${{ env.GITHUB_SHA_SHORT }}

    - name: Authorize docker to push to GAR
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev

    - name: Push the Docker image to GAR
      shell: bash
      run: docker push ${{ inputs.region }}-docker.pkg.dev/${{ inputs.project }}/quad/${{ inputs.app }}:${{ steps.date.outputs.date }}-${{ env.GITHUB_SHA_SHORT }}